import type {Route} from "../../.react-router/types/app/routes/+types";
import React from 'react';
import {Github, Linkedin, Mail, FileText, ArrowUpRight} from 'lucide-react';
import {Wallpaper} from "../components/home_bg";

export function meta({}: Route.MetaArgs) {
    return [
        {title: "Durgan McBroom"},
        {name: "description", content: "Hi, I'm Durgan."},
    ];
}

// --- TYPES ---
interface Project {
    title: string;
    description: string;
    link: string;
    tags: string[];
    date: string;
}

interface Social {
    name: string;
    link: string;
    icon: React.ReactNode;
}

// --- CONFIGURATION ---

const PERSONAL_DETAILS = {
    firstName: "Durgan",
    lastName: "McBroom",
    email: "durganmcbroom@gmail.com",
    bio: `Hey, I'm Durgan. I'm a first-year student at MIT planning to student computer science (course 6)
    and possibly physics (8). I love developing software, and have worked on many projects throughout the years--mostly 
    focusing on open-sourced API/framework development. Outside of STEM, I love to: play the saxophone and clarinet (at 
    Garfield High School and with MIT FJE); play Ultimate Frisbee (2024 HS state champs / 2x USA nationals); and cook 
    whenever I can find the time :).`,
    footerText: `© ${new Date().getFullYear()} Durgan McBroom`,
};

const ACCENT_COLOR = "text-orange-700";
const ACCENT_BG = "bg-orange-50";
const ACCENT_BORDER = "hover:border-orange-100";
const ACCENT_HOVER_TEXT = "hover:text-orange-700";
const SELECTION_COLOR = "selection:bg-orange-100 selection:text-orange-900";

const PROJECTS: Project[] = [
    {
        title: "Iterative Physics",
        description: "A kinematic equation solver and collision simulator inspired by concepts I learned after taking MIT's 8.01.",
        link: "https://durganmcbroom.com/iterative-physics",
        tags: ["ASTs", "Numerical analysis", "Collisions"],
        date: "December 2025 - January 2026"
    },
    {
        title: "Kaolin",
        description: "A Minecraft Modding platform designed for modularity, granular version control, and precise bytecode injection. Built from the ground up in Kotlin, and garnered popularity on Reddit before I stopped development during my first year of college.",
        link: "https://kaolinmc.com",
        tags: ["Minecraft", "Kotlin", "Modding"],
        date: "January 2021 - August 2025"
    },
    {
        title: "QuestCraft",
        description: "A small Minecraft network I built for my friends. Learned server orchestration techniques, Java, and basic networking.",
        link: "https://github.com/QuestCraft-Network",
        tags: ["Minecraft", "Server"],
        date: "August 2019 - October 2020"
    },
    {
        title: "ThisWebsite",
        description: "The source code for this portfolio. Partially generated by Google Gemini Pro. ",
        link: "https://github.com/durganmcbroom/durganmcbroom.github.io",
        tags: ["React", "TypeScript", "Tailwind"],
        date: "2023 - Present"
    },
    {
        title: "And ofc... My Scratch portfolio",
        description: "Scratch games I made as a kid.",
        link: "https://scratch.mit.edu/users/DurgansDesigns/",
        tags: ["Scratch"],
        date: "2013-2016"
    }
];

const SOCIALS: Social[] = [
    {name: "Github", link: "https://github.com/durganmcbroom", icon: <Github size={18}/>},
    {name: "LinkedIn", link: "https://linkedin.com/in/durganmcbroom", icon: <Linkedin size={18}/>},
    {name: "Email", link: `mailto:${PERSONAL_DETAILS.email}`, icon: <Mail size={18}/>},
    {name: "Resume", link: "/public/resume.pdf", icon: <FileText size={18}/>},
];


const SocialLink: React.FC<{ social: Social }> = ({social}) => (
    <a
        href={social.link}
        className={`flex items-center gap-2 text-slate-500 ${ACCENT_HOVER_TEXT} transition-colors text-sm font-medium`}
    >
        {social.icon}
        {social.name}
    </a>
);

const Header: React.FC = () => (
    <header className="mb-16 animate-in fade-in slide-in-from-bottom-4 duration-700">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-slate-900 mb-6">
            {PERSONAL_DETAILS.firstName} <span className={ACCENT_COLOR}>{PERSONAL_DETAILS.lastName}</span>
        </h1>
        <div className="flex flex-wrap gap-6">
            {SOCIALS.map((social) => (
                <SocialLink key={social.name} social={social}/>
            ))}
        </div>
    </header>
);

const Bio: React.FC = () => (
    <section className="mb-16 animate-in fade-in slide-in-from-bottom-8 duration-700 delay-100">
        <h2 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-6 flex items-center gap-2">
            <span className={`w-2 h-2 rounded-full ${ACCENT_COLOR} bg-current`}></span>
            About Me
        </h2>
        <p className="text-lg text-slate-700 leading-8 font-light max-w-prose">
            {PERSONAL_DETAILS.bio}
        </p>
    </section>
);

const ProjectCard: React.FC<{ project: Project }> = ({ project }) => (
    <a
        href={project.link}
        target="_blank"
        rel="noopener noreferrer"
        className={`group block p-6 -mx-6 rounded-2xl hover:bg-slate-50 transition-all duration-300 border border-transparent ${ACCENT_BORDER}`}
    >
        <div className="flex justify-between items-baseline mb-1">
            <h3 className={`text-lg font-semibold text-slate-900 ${ACCENT_HOVER_TEXT} transition-colors`}>
                {project.title}
            </h3>
            <span className={`text-slate-400 ${ACCENT_HOVER_TEXT} group-hover:translate-x-1 group-hover:-translate-y-1 transition-transform duration-300`}>
        <ArrowUpRight size={18} />
      </span>
        </div>

        <div className="text-xs font-mono text-slate-400 mb-3 uppercase tracking-wider">
            {project.date}
        </div>

        <p className="text-slate-600 mb-4 text-base font-normal leading-relaxed">
            {project.description}
        </p>
        <div className="flex gap-2 flex-wrap">
            {project.tags.map((tag, i) => (
                <span
                    key={i}
                    className={`text-xs font-medium ${ACCENT_COLOR} ${ACCENT_BG} px-2.5 py-1 rounded-full`}
                >
          {tag}
        </span>
            ))}
        </div>
    </a>
);

const ProjectsList: React.FC = () => (
    <section className="animate-in fade-in slide-in-from-bottom-8 duration-700 delay-200">
        <div className="flex items-center justify-between mb-4">
            <h2 className="text-xs font-bold text-slate-400 uppercase tracking-widest flex items-center gap-2">
                <span className={`w-2 h-2 rounded-full ${ACCENT_COLOR} bg-current`}></span>
                Personal Projects
            </h2>
        </div>
        <div className="space-y-4">
            {PROJECTS.map((project, index) => (
                <ProjectCard key={index} project={project}/>
            ))}
        </div>
    </section>
);

const Footer: React.FC = () => (
    <footer
        className="mt-16 pt-8 border-t border-slate-100 text-slate-400 text-sm flex flex-col sm:flex-row justify-between items-center gap-4 animate-in fade-in duration-1000 delay-300">
        <p>{PERSONAL_DETAILS.footerText}</p>
        <div className="flex gap-6 font-medium">
            <a href="#" className={`hover:text-slate-600 transition-colors`}>Home</a>
            <a href="/public/resume.pdf" className={`hover:text-slate-600 transition-colors`}>Resume</a>
            <a href={`mailto:${PERSONAL_DETAILS.email}`}
               className={`hover:text-slate-600 transition-colors`}>Contact</a>
        </div>
    </footer>
);

export default function Home() {
    return (
        <div className={`min-h-screen bg-white text-slate-900 font-sans ${SELECTION_COLOR}`}>
            <main className="max-w-4xl mx-auto px-6 py-20 md:py-32">
                <Wallpaper />
                <Header/>
                <Bio/>
                <ProjectsList/>
                <Footer/>
            </main>
        </div>
    );
}
